[pytest]
testpaths = .
python_files = test.py test_*.py
python_classes = Test*
addopts =
    --strict-markers
    -ra

[coverage:run]
source = cyk
omit =
    tests/*
    test.py

[coverage:report]
show_missing = True
skip_covered = False
precision = 1
fail_under = 0
